#include <stdio.h>
#include <bmotion_api.h>
#include <string.h>
#include <stdlib.h>

void setRandomStuffTimer();
	
void doRandomStuff(void*)
{
	setRandomStuffTimer();
	bMotion.DoAction(NULL, NULL, "%VAR{randomStuff}");
}

void setRandomStuffTimer()
{
	unsigned int mindelay = (unsigned int)bMotion.Info("minRandomDelay");
	unsigned int maxdelay = (unsigned int)bMotion.Info("maxRandomDelay");
	unsigned int upperlimit = maxdelay - mindelay;
	unsigned int timeout = (rand() % upperlimit) + mindelay;
	bMotion.AddTimer(timeout * 60000, doRandomStuff, NULL);
	bMotion.Log(1, "bMotion: randomStuff next (%u minutes)", timeout);
}

extern "C" void Init()
{
	setRandomStuffTimer();
	bMotion.AbstractRegister("randomStuff");
	bMotion.AbstractBatchAdd("randomStuff",
		"I'm a doctor not %VAR{sillyThings}",
		"pika pika!" "pikachu!",
		"pika...CHUUUU!!! *ZZZAAP*",
		"*boing*",
		"moo.",
		"BOOM" "BLAM",
		"/goes for coffee",
		"bof",
		"alors",
		"bhar",
		"arrrr..",
		"elbow.",
		"gorilla",
		"*yawn*",
		"*spangle*",
		"brb",
		"lum de dum de dum...",
		"/twiddles thumbs",
		"boom",
		"Look over there!",
		"bleh",
		"/puts on some banging house tunes",
		"zut alors",
		"alors bof",
		"groogle arrhar",
		"brb, loo",
		"brb, sex",
		"uNF",
		"~rarr~",
		"~oof~",
		"Oops, I've ruined it.",
		"Buttock Crunchies",
		"D'oh!",
		"setty mings lalalala",
		"pika",
		"Are you local?",
		"We'll have no trouble here",
		"Resistance is futile, you will be assimilated",
		"Resistance is futile, you will be 0wn3d",
		"Assimilation is futile, you will be resi... D'OH!",
		"I *didn't*",
		"blblblblblbl",
		"/assimilates the channel",
		"We are the B0rg. You will be 4551m1la70r3d.",
		"wheeeee",
		"We are the Borg. Lower your shields and surrender your ship.",
		"did you see that..",
		"You are the weakest link, goodbye.",
		"Computer, deactivate iguana.",
		"kerPOW",
		"kerSPLAT",
		"KAZAM",
		"kazOO",
		"yaZOO",
		"spam, spam, spam, spam, spam, spam...",
		"ALL YOUR BASE ARE BELONG TO US",
		"For great justice.",
		"nostril",
		"ah bof",
		"I didn't!",
		"shh, sekrit",
		"SSSH SEKRIT",
		"SILENCE%colen",
		"pop",
		"cabbages",
		"penguin",
		"cheese",
		"mmm chicken",
		"blimey",
		"crikey",
		"hoorah",
		"pie pie pie pie",
		"fantastic",
		"ho ho",
		"har har",
		"deary me",
		"m00se",
		"llama",
		"frogs",
		"knickers",
		"bob",
		"kenneth",
		"nigel",
		"is everyone thooper?",
		"super",
		"thooper",
		"lashings of ginger beer",
		"There are clowns living under my bed.",
		"What's it going to take to get you into this car?",
		"Was I snoring again?",
		"I think it's starting to work.",
		"Does it hurt when I do this?",
		"Come on down, you're only going to hurt yourself.",
		"It's a bird, it's a plane, it's... no, it's a bird after all.",
		"It's a %VAR{sillyThings}, it's a plane, no... it's a bird.",
		"It tasted like butter.",
		"Are those real handcuffs?",
		"Oh good, Captain Adventure has arrived.",
		"I'm running off with the mailman.",
		"It's not my fault, it just exploded.",
		"You are SO fired.",
		"I'm sweating like a pig!",
		"Please stay seated until the ride has stopped.",
		"Don't touch that. It's dirty.",
		"My underwear is too tight %VAR{unsmiles}",
		"Stop staring at the monkeys%colen",
		"I can't reach this itch $VAR{unsmiles}",
		"That is the weirdest smell ever.",
		"There's nothing sexier than %VAR{sillyThings}",
		"I feel like I'm about to vomit everywhere.",
		"Waiter, my soup's got %VAR{sillyThings} in it.",
		"I look good in hot pants.",
		"I just have a thing about toes.",
		"Oh boy, my subscription is running out.",
		"I think it's getting bigger.",
		"Blondes DO have more fun!",
		"That's a funny little cigarette.",
		"mmm... cheesy",
		"Assume the position%colen",
		"Chicks can't resist me.",
		"Stop wiggling for a minute.",
		"I didn't touch it.",
		"You have something in your nose.",
		"this reminds me of my wedding night",
		"my zipper's stuck %VAR{unsmiles}",
		"is this going to be on the test?",
		"my %VAR{bodypart} is hurting %VAR{unsmiles}",
		ABSTRACT_END);
	bMotion.AbstractRegister("sillyThings");
	bMotion.AbstractBatchAdd("sillyThings",
		"12 year old black metal kids",
		"14 US dollars",
		"1.5 pie",
		"20 minutes till lunch",
		"5 litres of Halfords 10W-40",
		"5 pints" "99 bicycle clips",
		"a 12-inch pianist",
		"a 1.44MB floppy disk",
		"a 1979 Aston Martin",
		"a 7MB Flash movie",
		"AA",
		"a backup",
		"a badger",
		"a bag",
		"a bagette",
		"a bank",
		"a barbecue",
		"a bath",
		"a baton",
		"a bazooka",
		"a beach",
		"a beard",
		"a beast",
		"a bed",
		"Aberystwyth",
		"a better computer",
		"a big stick with nails in it",
		"a bike",
		"a bird",
		"a biscuit tin",
		"a blanket",
		"a bloke",
		"a bog wallness",
		"a boiler",
		"a boob",
		"a book",
		"a bookshelf",
		"a bookstore",
		"a boot",
		"a bot",
		"a bottle",
		"a bottom",
		"a box",
		"a boy",
		"a branch",
		"a brick",
		"a bridge",
		"a broken CD case",
		"a brother",
		"a brownie",
		"a bucket",
		"a budget",
		"a building",
		"a bullet",
		"a bunker",
		"a bus",
		"a business",
		"a button",
		"a cab",
		"a camara",
		"a camera",
		"a candidate",
		"a can of coke",
		"a can of diet coke (bleh)",
		"a capital",
		"a Cappucino",
		"a captain",
		"a car",
		"a car park",
		"a carrot",
		"a cartoon",
		"a case",
		"a cassette",
		"a cassette deck",
		"a cat",
		"a catflap",
		"a cd wallet",
		"a ceiling",
		"a cellar",
		"a certain",
		"a chain",
		"a champion",
		"a channel",
		"a chat",
		"a chatterbot",
		"a cheque",
		"a choir",
		"a Christian",
		"a chum",
		"a cinema",
		"a circus",
		"a client",
		"a clock",
		"a clothes peg",
		"a clown",
		"a coffee pot",
		"a company",
		"a compiler",
		"a complete central heating system",
		ABSTRACT_END);
}

